import {
  IconBrandNextjs,
  IconBrandTypescript,
  IconBrandTailwind,
  IconBrandReactNative,
  IconApi,
  IconDatabase,
  IconBrandPrisma,
  IconAuth2fa,
  IconBrandReact,
  IconBrandFramerMotion,
  IconBrandHtml5,
  IconBrandCss3,
  IconBrandJavascript,
  IconBrandNodejs,
  IconBrandThreejs,
  IconBrandOauth,
  IconBrandPhp,
} from "@tabler/icons-react";

export const iconMapping: { [key: string]: JSX.Element } = {
  nextjs: <IconBrandNextjs size={40} key="nextjs" />,
  typescript: <IconBrandTypescript size={40} key="typescript" />,
  tailwind: <IconBrandTailwind size={40} key="tailwind" />,
  reactnative: <IconBrandReactNative size={40} key="reactnative" />,
  api: <IconApi size={40} key="api" />,
  database: <IconDatabase size={40} key="database" />,
  prisma: <IconBrandPrisma size={40} key="prisma" />,
  authorization: <IconAuth2fa size={40} key="authorization" />,
  react: <IconBrandReact size={40} key="react" />,
  framermotion: <IconBrandFramerMotion size={40} key="framermotion" />,
  html: <IconBrandHtml5 size={40} key="html" />,
  css: <IconBrandCss3 size={40} key="css" />,
  javascript: <IconBrandJavascript size={40} key="javascript" />,
  nodejs: <IconBrandNodejs size={40} key="nodejs" />,
  threejs: <IconBrandThreejs size={40} key="threejs" />,
  oauth: <IconBrandOauth size={40} key="oauth" />,
  php: <IconBrandPhp size={40} key="php" />,
};
